name: build

on:
  push:
  workflow_dispatch:

env:
  github_token: ${{secrets.GITHUB_TOKEN}}

jobs:
  build-windows:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: mingw64, arch: x86_64 }
        ]
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        release: false
        update: false
        install: >-
          base-devel
          git
          mingw-w64-${{ matrix.arch }}-gcc
          make
          libtool
          autoconf
          automake-wrapper
          mingw-w64-${{ matrix.arch }}-libzip
          mingw-w64-${{ matrix.arch }}-github-cli

    - name: prepare environment
      run: |
        echo "target_triplet=`gcc -dumpmachine`" >> $GITHUB_ENV
        git config --global core.autocrlf false
        mkdir -p $HOME/rel

    # deps relevant to libimobiledevice specifically
    - name: build libplist
      run: |
        git clone --depth=1 --recursive https://github.com/libimobiledevice/libplist
        cd libplist/
        ./autogen.sh CC=gcc CXX=g++ --enable-debug --without-cython --enable-static --disable-shared --prefix="$HOME/rel"
        make -j install LDFLAGS="-all-static -Wl,--allow-multiple-definition"
        cp -a $HOME/rel/* /mingw64/

    - name: build libimobiledevice-glue
      run: |
        git clone --depth=1 --recursive https://github.com/libimobiledevice/libimobiledevice-glue
        cd libimobiledevice-glue/
        ./autogen.sh CC=gcc CXX=g++ --enable-debug --without-cython --enable-static --disable-shared --prefix="$HOME/rel"
        make -j install LDFLAGS="-all-static -Wl,--allow-multiple-definition"
        cp -a $HOME/rel/* /mingw64/

    - name: build libusbmuxd
      run: |
        git clone --depth=1 --recursive https://github.com/libimobiledevice/libusbmuxd
        cd libusbmuxd/
        ./autogen.sh CC=gcc CXX=g++ --enable-debug --without-cython --enable-static --disable-shared --prefix="$HOME/rel"
        make -j install LDFLAGS="-all-static -Wl,--allow-multiple-definition"
        cp -a $HOME/rel/* /mingw64/

    - uses: actions/checkout@v3
    - name: autogen and make install
      run: |
        ./autogen.sh CC=gcc CXX=g++ --enable-debug --without-cython --enable-static --disable-shared --prefix="$HOME/rel"
        make -j install LDFLAGS="-all-static -Wl,--allow-multiple-definition"
        cp -a $HOME/rel/* /mingw64/

    # other unrelated libimobiledevice projects
    - name: build libxml2
      run: |
        git clone --depth=1 --recursive https://github.com/GNOME/libxml2
        cd libxml2/
        ./autogen.sh CC=gcc CXX=g++ --enable-static --enable-shared=no --prefix="$HOME/rel"
        make -j install LDFLAGS="-all-static -Wl,--allow-multiple-definition"
        cp -a $HOME/rel/* /mingw64/

    - name: build libideviceactivation
      run: |
        git clone --depth=1 --recursive https://github.com/libimobiledevice/libideviceactivation
        cd libideviceactivation/
        ./autogen.sh CC=gcc CXX=g++ --enable-debug --without-cython --enable-static --disable-shared --prefix="$HOME/rel"
        make -j install CFLAGS="-DLIBXML_STATIC -DCURL_STATICLIB" LDFLAGS="-all-static -Wl,--allow-multiple-definition"
        cp -a $HOME/rel/* /mingw64/

    - name: build ideviceinstaller
      run: |
        git clone --depth=1 --recursive https://github.com/libimobiledevice/ideviceinstaller
        cd ideviceinstaller/
        ./autogen.sh CC=gcc CXX=g++ --enable-debug --without-cython --enable-static --disable-shared --prefix="$HOME/rel"
        make -j install LDFLAGS="-all-static -Wl,--allow-multiple-definition"
        cp -a $HOME/rel/* /mingw64/

    - name: build libirecovery
      run: |
        git clone --depth=1 --recursive https://github.com/libimobiledevice/libirecovery
        cd libirecovery/
        ./autogen.sh CC=gcc CXX=g++ --enable-debug --without-cython --enable-static --disable-shared --prefix="$HOME/rel"
        make -j install LDFLAGS="-all-static -Wl,--allow-multiple-definition"
        cp -a $HOME/rel/* /mingw64/

    - name: build idevicerestore
      run: |
        git clone --depth=1 --recursive https://github.com/libimobiledevice/idevicerestore
        cd idevicerestore/
        ./autogen.sh CC=gcc CXX=g++ --enable-debug --without-cython --enable-static --disable-shared --prefix="$HOME/rel"
        make -j install LDFLAGS="-all-static -Wl,--allow-multiple-definition"
        cp -a $HOME/rel/* /mingw64/

    - name: prepare release
      run: |
        tar -C "$HOME/rel" -cJvf libimobile-suite-latest_${{ matrix.arch }}-${{ matrix.msystem }}.tar.xz .

    - name: publish release
      run: |
        TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
        gh release create "$TAG" --draft --title "Draft Release"
        gh release upload "$TAG" libimobile-suite-latest_${{ matrix.arch }}-${{ matrix.msystem }}.tar.xz
